version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    privileged: true                       # erlaubt Zugriff auf GPIO
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=mydb
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=mydb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d      # optional: init.sql wird beim 1. Start importiert
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
